# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/google-a2a/A2A/refs/heads/main/specification/json/a2a.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import Field

from a2a.utils.pydantic_base import A2ABaseModel


class A2A(A2ABaseModel):
    __root__: Any


class In(str, Enum):
    """
    The location of the API key. Valid values are "query", "header", or "cookie".
    """

    cookie = 'cookie'
    header = 'header'
    query = 'query'


class APIKeySecurityScheme(A2ABaseModel):
    """
    API Key security scheme.
    """

    description: str | None = None
    """
    Description of this security scheme.
    """
    in_: In = Field(..., alias='in')
    """
    The location of the API key. Valid values are "query", "header", or "cookie".
    """
    name: str
    """
    The name of the header, query or cookie parameter to be used.
    """
    type: str = Field(default='apiKey', const=True)


class AgentExtension(A2ABaseModel):
    """
    A declaration of an extension supported by an Agent.
    """

    description: str | None = None
    """
    A description of how this agent uses this extension.
    """
    params: dict[str, Any] | None = None
    """
    Optional configuration for the extension.
    """
    required: bool | None = None
    """
    Whether the client must follow specific requirements of the extension.
    """
    uri: str
    """
    The URI of the extension.
    """


class AgentProvider(A2ABaseModel):
    """
    Represents the service provider of an agent.
    """

    organization: str
    """
    Agent provider's organization name.
    """
    url: str
    """
    Agent provider's URL.
    """


class AgentSkill(A2ABaseModel):
    """
    Represents a unit of capability that an agent can perform.
    """

    description: str
    """
    Description of the skill - will be used by the client or a human
    as a hint to understand what the skill does.
    """
    examples: list[str] | None = None
    """
    The set of example scenarios that the skill can perform.
    Will be used by the client as a hint to understand how the skill can be used.
    """
    id: str
    """
    Unique identifier for the agent's skill.
    """
    input_modes: list[str] | None = Field(default=None, alias='inputModes')
    """
    The set of interaction modes that the skill supports
    (if different than the default).
    Supported media types for input.
    """
    name: str
    """
    Human readable name of the skill.
    """
    output_modes: list[str] | None = Field(default=None, alias='outputModes')
    """
    Supported media types for output.
    """
    tags: list[str]
    """
    Set of tagwords describing classes of capabilities for this specific skill.
    """


class AuthorizationCodeOAuthFlow(A2ABaseModel):
    """
    Configuration details for a supported OAuth Flow
    """

    authorization_url: str = Field(..., alias='authorizationUrl')
    """
    The authorization URL to be used for this flow. This MUST be in the form of a URL. The OAuth2
    standard requires the use of TLS
    """
    refresh_url: str | None = Field(default=None, alias='refreshUrl')
    """
    The URL to be used for obtaining refresh tokens. This MUST be in the form of a URL. The OAuth2
    standard requires the use of TLS.
    """
    scopes: dict[str, str]
    """
    The available scopes for the OAuth2 security scheme. A map between the scope name and a short
    description for it. The map MAY be empty.
    """
    token_url: str = Field(..., alias='tokenUrl')
    """
    The token URL to be used for this flow. This MUST be in the form of a URL. The OAuth2 standard
    requires the use of TLS.
    """


class ClientCredentialsOAuthFlow(A2ABaseModel):
    """
    Configuration details for a supported OAuth Flow
    """

    refresh_url: str | None = Field(default=None, alias='refreshUrl')
    """
    The URL to be used for obtaining refresh tokens. This MUST be in the form of a URL. The OAuth2
    standard requires the use of TLS.
    """
    scopes: dict[str, str]
    """
    The available scopes for the OAuth2 security scheme. A map between the scope name and a short
    description for it. The map MAY be empty.
    """
    token_url: str = Field(..., alias='tokenUrl')
    """
    The token URL to be used for this flow. This MUST be in the form of a URL. The OAuth2 standard
    requires the use of TLS.
    """


class ContentTypeNotSupportedError(A2ABaseModel):
    """
    A2A specific error indicating incompatible content types between request and agent capabilities.
    """

    code: int = Field(default=-32005, const=True)
    """
    A Number that indicates the error type that occurred.
    """
    data: Any | None = None
    """
    A Primitive or Structured value that contains additional information about the error.
    This may be omitted.
    """
    message: str | None = 'Incompatible content types'
    """
    A String providing a short description of the error.
    """


class DataPart(A2ABaseModel):
    """
    Represents a structured data segment within a message part.
    """

    data: dict[str, Any]
    """
    Structured data content
    """
    kind: str = Field(default='data', const=True)
    """
    Part type - data for DataParts
    """
    metadata: dict[str, Any] | None = None
    """
    Optional metadata associated with the part.
    """


class DeleteTaskPushNotificationConfigParams(A2ABaseModel):
    """
    Parameters for removing pushNotificationConfiguration associated with a Task
    """

    id: str
    """
    Task id.
    """
    metadata: dict[str, Any] | None = None
    push_notification_config_id: str = Field(..., alias='pushNotificationConfigId')


class DeleteTaskPushNotificationConfigRequest(A2ABaseModel):
    """
    JSON-RPC request model for the 'tasks/pushNotificationConfig/delete' method.
    """

    id: str | int
    """
    An identifier established by the Client that MUST contain a String, Number.
    Numbers SHOULD NOT contain fractional parts.
    """
    jsonrpc: str = Field(default='2.0', const=True)
    """
    Specifies the version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    method: str = Field(default='tasks/pushNotificationConfig/delete', const=True)
    """
    A String containing the name of the method to be invoked.
    """
    params: DeleteTaskPushNotificationConfigParams
    """
    A Structured value that holds the parameter values to be used during the invocation of the method.
    """


class DeleteTaskPushNotificationConfigSuccessResponse(A2ABaseModel):
    """
    JSON-RPC success response model for the 'tasks/pushNotificationConfig/delete' method.
    """

    id: str | int | None
    """
    An identifier established by the Client that MUST contain a String, Number.
    Numbers SHOULD NOT contain fractional parts.
    """
    jsonrpc: str = Field(default='2.0', const=True)
    """
    Specifies the version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    result: None
    """
    The result object on success.
    """


class FileBase(A2ABaseModel):
    """
    Represents the base entity for FileParts
    """

    mime_type: str | None = Field(default=None, alias='mimeType')
    """
    Optional mimeType for the file
    """
    name: str | None = None
    """
    Optional name for the file
    """


class FileWithBytes(A2ABaseModel):
    """
    Define the variant where 'bytes' is present and 'uri' is absent
    """

    bytes: str
    """
    base64 encoded content of the file
    """
    mime_type: str | None = Field(default=None, alias='mimeType')
    """
    Optional mimeType for the file
    """
    name: str | None = None
    """
    Optional name for the file
    """


class FileWithUri(A2ABaseModel):
    """
    Define the variant where 'uri' is present and 'bytes' is absent
    """

    mime_type: str | None = Field(default=None, alias='mimeType')
    """
    Optional mimeType for the file
    """
    name: str | None = None
    """
    Optional name for the file
    """
    uri: str
    """
    URL for the File content
    """


class GetTaskPushNotificationConfigParams(A2ABaseModel):
    """
    Parameters for fetching a pushNotificationConfiguration associated with a Task
    """

    id: str
    """
    Task id.
    """
    metadata: dict[str, Any] | None = None
    push_notification_config_id: str | None = Field(
        default=None, alias='pushNotificationConfigId'
    )


class HTTPAuthSecurityScheme(A2ABaseModel):
    """
    HTTP Authentication security scheme.
    """

    bearer_format: str | None = Field(default=None, alias='bearerFormat')
    """
    A hint to the client to identify how the bearer token is formatted. Bearer tokens are usually
    generated by an authorization server, so this information is primarily for documentation
    purposes.
    """
    description: str | None = None
    """
    Description of this security scheme.
    """
    scheme: str
    """
    The name of the HTTP Authentication scheme to be used in the Authorization header as defined
    in RFC7235. The values used SHOULD be registered in the IANA Authentication Scheme registry.
    The value is case-insensitive, as defined in RFC7235.
    """
    type: str = Field(default='http', const=True)


class ImplicitOAuthFlow(A2ABaseModel):
    """
    Configuration details for a supported OAuth Flow
    """

    authorization_url: str = Field(..., alias='authorizationUrl')
    """
    The authorization URL to be used for this flow. This MUST be in the form of a URL. The OAuth2
    standard requires the use of TLS
    """
    refresh_url: str | None = Field(default=None, alias='refreshUrl')
    """
    The URL to be used for obtaining refresh tokens. This MUST be in the form of a URL. The OAuth2
    standard requires the use of TLS.
    """
    scopes: dict[str, str]
    """
    The available scopes for the OAuth2 security scheme. A map between the scope name and a short
    description for it. The map MAY be empty.
    """


class InternalError(A2ABaseModel):
    """
    JSON-RPC error indicating an internal JSON-RPC error on the server.
    """

    code: int = Field(default=-32603, const=True)
    """
    A Number that indicates the error type that occurred.
    """
    data: Any | None = None
    """
    A Primitive or Structured value that contains additional information about the error.
    This may be omitted.
    """
    message: str | None = 'Internal error'
    """
    A String providing a short description of the error.
    """


class InvalidAgentResponseError(A2ABaseModel):
    """
    A2A specific error indicating agent returned invalid response for the current method
    """

    code: int = Field(default=-32006, const=True)
    """
    A Number that indicates the error type that occurred.
    """
    data: Any | None = None
    """
    A Primitive or Structured value that contains additional information about the error.
    This may be omitted.
    """
    message: str | None = 'Invalid agent response'
    """
    A String providing a short description of the error.
    """


class InvalidParamsError(A2ABaseModel):
    """
    JSON-RPC error indicating invalid method parameter(s).
    """

    code: int = Field(default=-32602, const=True)
    """
    A Number that indicates the error type that occurred.
    """
    data: Any | None = None
    """
    A Primitive or Structured value that contains additional information about the error.
    This may be omitted.
    """
    message: str | None = 'Invalid parameters'
    """
    A String providing a short description of the error.
    """


class InvalidRequestError(A2ABaseModel):
    """
    JSON-RPC error indicating the JSON sent is not a valid Request object.
    """

    code: int = Field(default=-32600, const=True)
    """
    A Number that indicates the error type that occurred.
    """
    data: Any | None = None
    """
    A Primitive or Structured value that contains additional information about the error.
    This may be omitted.
    """
    message: str | None = 'Request payload validation error'
    """
    A String providing a short description of the error.
    """


class JSONParseError(A2ABaseModel):
    """
    JSON-RPC error indicating invalid JSON was received by the server.
    """

    code: int = Field(default=-32700, const=True)
    """
    A Number that indicates the error type that occurred.
    """
    data: Any | None = None
    """
    A Primitive or Structured value that contains additional information about the error.
    This may be omitted.
    """
    message: str | None = 'Invalid JSON payload'
    """
    A String providing a short description of the error.
    """


class JSONRPCError(A2ABaseModel):
    """
    Represents a JSON-RPC 2.0 Error object.
    This is typically included in a JSONRPCErrorResponse when an error occurs.
    """

    code: int
    """
    A Number that indicates the error type that occurred.
    """
    data: Any | None = None
    """
    A Primitive or Structured value that contains additional information about the error.
    This may be omitted.
    """
    message: str
    """
    A String providing a short description of the error.
    """


class JSONRPCMessage(A2ABaseModel):
    """
    Base interface for any JSON-RPC 2.0 request or response.
    """

    id: str | int | None = None
    """
    An identifier established by the Client that MUST contain a String, Number.
    Numbers SHOULD NOT contain fractional parts.
    """
    jsonrpc: str = Field(default='2.0', const=True)
    """
    Specifies the version of the JSON-RPC protocol. MUST be exactly "2.0".
    """


class JSONRPCRequest(A2ABaseModel):
    """
    Represents a JSON-RPC 2.0 Request object.
    """

    id: str | int | None = None
    """
    An identifier established by the Client that MUST contain a String, Number.
    Numbers SHOULD NOT contain fractional parts.
    """
    jsonrpc: str = Field(default='2.0', const=True)
    """
    Specifies the version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    method: str
    """
    A String containing the name of the method to be invoked.
    """
    params: dict[str, Any] | None = None
    """
    A Structured value that holds the parameter values to be used during the invocation of the method.
    """


class JSONRPCSuccessResponse(A2ABaseModel):
    """
    Represents a JSON-RPC 2.0 Success Response object.
    """

    id: str | int | None
    """
    An identifier established by the Client that MUST contain a String, Number.
    Numbers SHOULD NOT contain fractional parts.
    """
    jsonrpc: str = Field(default='2.0', const=True)
    """
    Specifies the version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    result: Any
    """
    The result object on success
    """


class ListTaskPushNotificationConfigParams(A2ABaseModel):
    """
    Parameters for getting list of pushNotificationConfigurations associated with a Task
    """

    id: str
    """
    Task id.
    """
    metadata: dict[str, Any] | None = None


class ListTaskPushNotificationConfigRequest(A2ABaseModel):
    """
    JSON-RPC request model for the 'tasks/pushNotificationConfig/list' method.
    """

    id: str | int
    """
    An identifier established by the Client that MUST contain a String, Number.
    Numbers SHOULD NOT contain fractional parts.
    """
    jsonrpc: str = Field(default='2.0', const=True)
    """
    Specifies the version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    method: str = Field(default='tasks/pushNotificationConfig/list', const=True)
    """
    A String containing the name of the method to be invoked.
    """
    params: ListTaskPushNotificationConfigParams
    """
    A Structured value that holds the parameter values to be used during the invocation of the method.
    """


class Role(str, Enum):
    """
    Message sender's role
    """

    agent = 'agent'
    user = 'user'


class MethodNotFoundError(A2ABaseModel):
    """
    JSON-RPC error indicating the method does not exist or is not available.
    """

    code: int = Field(default=-32601, const=True)
    """
    A Number that indicates the error type that occurred.
    """
    data: Any | None = None
    """
    A Primitive or Structured value that contains additional information about the error.
    This may be omitted.
    """
    message: str | None = 'Method not found'
    """
    A String providing a short description of the error.
    """


class OpenIdConnectSecurityScheme(A2ABaseModel):
    """
    OpenID Connect security scheme configuration.
    """

    description: str | None = None
    """
    Description of this security scheme.
    """
    open_id_connect_url: str = Field(..., alias='openIdConnectUrl')
    """
    Well-known URL to discover the [[OpenID-Connect-Discovery]] provider metadata.
    """
    type: str = Field(default='openIdConnect', const=True)


class PartBase(A2ABaseModel):
    """
    Base properties common to all message parts.
    """

    metadata: dict[str, Any] | None = None
    """
    Optional metadata associated with the part.
    """


class PasswordOAuthFlow(A2ABaseModel):
    """
    Configuration details for a supported OAuth Flow
    """

    refresh_url: str | None = Field(default=None, alias='refreshUrl')
    """
    The URL to be used for obtaining refresh tokens. This MUST be in the form of a URL. The OAuth2
    standard requires the use of TLS.
    """
    scopes: dict[str, str]
    """
    The available scopes for the OAuth2 security scheme. A map between the scope name and a short
    description for it. The map MAY be empty.
    """
    token_url: str = Field(..., alias='tokenUrl')
    """
    The token URL to be used for this flow. This MUST be in the form of a URL. The OAuth2 standard
    requires the use of TLS.
    """


class PushNotificationAuthenticationInfo(A2ABaseModel):
    """
    Defines authentication details for push notifications.
    """

    credentials: str | None = None
    """
    Optional credentials
    """
    schemes: list[str]
    """
    Supported authentication schemes - e.g. Basic, Bearer
    """


class PushNotificationConfig(A2ABaseModel):
    """
    Configuration for setting up push notifications for task updates.
    """

    authentication: PushNotificationAuthenticationInfo | None = None
    id: str | None = None
    """
    Push Notification ID - created by server to support multiple callbacks
    """
    token: str | None = None
    """
    Token unique to this task/session.
    """
    url: str
    """
    URL for sending the push notifications.
    """


class PushNotificationNotSupportedError(A2ABaseModel):
    """
    A2A specific error indicating the agent does not support push notifications.
    """

    code: int = Field(default=-32003, const=True)
    """
    A Number that indicates the error type that occurred.
    """
    data: Any | None = None
    """
    A Primitive or Structured value that contains additional information about the error.
    This may be omitted.
    """
    message: str | None = 'Push Notification is not supported'
    """
    A String providing a short description of the error.
    """


class SecuritySchemeBase(A2ABaseModel):
    """
    Base properties shared by all security schemes.
    """

    description: str | None = None
    """
    Description of this security scheme.
    """


class TaskIdParams(A2ABaseModel):
    """
    Parameters containing only a task ID, used for simple task operations.
    """

    id: str
    """
    Task id.
    """
    metadata: dict[str, Any] | None = None


class TaskNotCancelableError(A2ABaseModel):
    """
    A2A specific error indicating the task is in a state where it cannot be canceled.
    """

    code: int = Field(default=-32002, const=True)
    """
    A Number that indicates the error type that occurred.
    """
    data: Any | None = None
    """
    A Primitive or Structured value that contains additional information about the error.
    This may be omitted.
    """
    message: str | None = 'Task cannot be canceled'
    """
    A String providing a short description of the error.
    """


class TaskNotFoundError(A2ABaseModel):
    """
    A2A specific error indicating the requested task ID was not found.
    """

    code: int = Field(default=-32001, const=True)
    """
    A Number that indicates the error type that occurred.
    """
    data: Any | None = None
    """
    A Primitive or Structured value that contains additional information about the error.
    This may be omitted.
    """
    message: str | None = 'Task not found'
    """
    A String providing a short description of the error.
    """


class TaskPushNotificationConfig(A2ABaseModel):
    """
    Parameters for setting or getting push notification configuration for a task
    """

    push_notification_config: PushNotificationConfig = Field(
        ..., alias='pushNotificationConfig'
    )
    """
    Push notification configuration.
    """
    task_id: str = Field(..., alias='taskId')
    """
    Task id.
    """


class TaskQueryParams(A2ABaseModel):
    """
    Parameters for querying a task, including optional history length.
    """

    history_length: int | None = Field(default=None, alias='historyLength')
    """
    Number of recent messages to be retrieved.
    """
    id: str
    """
    Task id.
    """
    metadata: dict[str, Any] | None = None


class TaskResubscriptionRequest(A2ABaseModel):
    """
    JSON-RPC request model for the 'tasks/resubscribe' method.
    """

    id: str | int
    """
    An identifier established by the Client that MUST contain a String, Number.
    Numbers SHOULD NOT contain fractional parts.
    """
    jsonrpc: str = Field(default='2.0', const=True)
    """
    Specifies the version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    method: str = Field(default='tasks/resubscribe', const=True)
    """
    A String containing the name of the method to be invoked.
    """
    params: TaskIdParams
    """
    A Structured value that holds the parameter values to be used during the invocation of the method.
    """


class TaskState(str, Enum):
    """
    Represents the possible states of a Task.
    """

    submitted = 'submitted'
    working = 'working'
    input_required = 'input-required'
    completed = 'completed'
    canceled = 'canceled'
    failed = 'failed'
    rejected = 'rejected'
    auth_required = 'auth-required'
    unknown = 'unknown'


class TextPart(A2ABaseModel):
    """
    Represents a text segment within parts.
    """

    kind: str = Field(default='text', const=True)
    """
    Part type - text for TextParts
    """
    metadata: dict[str, Any] | None = None
    """
    Optional metadata associated with the part.
    """
    text: str
    """
    Text content
    """


class UnsupportedOperationError(A2ABaseModel):
    """
    A2A specific error indicating the requested operation is not supported by the agent.
    """

    code: int = Field(default=-32004, const=True)
    """
    A Number that indicates the error type that occurred.
    """
    data: Any | None = None
    """
    A Primitive or Structured value that contains additional information about the error.
    This may be omitted.
    """
    message: str | None = 'This operation is not supported'
    """
    A String providing a short description of the error.
    """


class A2AError(A2ABaseModel):
    __root__: (
        JSONParseError
        | InvalidRequestError
        | MethodNotFoundError
        | InvalidParamsError
        | InternalError
        | TaskNotFoundError
        | TaskNotCancelableError
        | PushNotificationNotSupportedError
        | UnsupportedOperationError
        | ContentTypeNotSupportedError
        | InvalidAgentResponseError
    )


class AgentCapabilities(A2ABaseModel):
    """
    Defines optional capabilities supported by an agent.
    """

    extensions: list[AgentExtension] | None = None
    """
    extensions supported by this agent.
    """
    push_notifications: bool | None = Field(default=None, alias='pushNotifications')
    """
    true if the agent can notify updates to client.
    """
    state_transition_history: bool | None = Field(
        default=None, alias='stateTransitionHistory'
    )
    """
    true if the agent exposes status change history for tasks.
    """
    streaming: bool | None = None
    """
    true if the agent supports SSE.
    """


class CancelTaskRequest(A2ABaseModel):
    """
    JSON-RPC request model for the 'tasks/cancel' method.
    """

    id: str | int
    """
    An identifier established by the Client that MUST contain a String, Number.
    Numbers SHOULD NOT contain fractional parts.
    """
    jsonrpc: str = Field(default='2.0', const=True)
    """
    Specifies the version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    method: str = Field(default='tasks/cancel', const=True)
    """
    A String containing the name of the method to be invoked.
    """
    params: TaskIdParams
    """
    A Structured value that holds the parameter values to be used during the invocation of the method.
    """


class FilePart(A2ABaseModel):
    """
    Represents a File segment within parts.
    """

    file: FileWithBytes | FileWithUri
    """
    File content either as url or bytes
    """
    kind: str = Field(default='file', const=True)
    """
    Part type - file for FileParts
    """
    metadata: dict[str, Any] | None = None
    """
    Optional metadata associated with the part.
    """


class GetTaskPushNotificationConfigRequest(A2ABaseModel):
    """
    JSON-RPC request model for the 'tasks/pushNotificationConfig/get' method.
    """

    id: str | int
    """
    An identifier established by the Client that MUST contain a String, Number.
    Numbers SHOULD NOT contain fractional parts.
    """
    jsonrpc: str = Field(default='2.0', const=True)
    """
    Specifies the version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    method: str = Field(default='tasks/pushNotificationConfig/get', const=True)
    """
    A String containing the name of the method to be invoked.
    """
    params: TaskIdParams | GetTaskPushNotificationConfigParams
    """
    A Structured value that holds the parameter values to be used during the invocation of the method.
    TaskIdParams type is deprecated for this method
    """


class GetTaskPushNotificationConfigSuccessResponse(A2ABaseModel):
    """
    JSON-RPC success response model for the 'tasks/pushNotificationConfig/get' method.
    """

    id: str | int | None
    """
    An identifier established by the Client that MUST contain a String, Number.
    Numbers SHOULD NOT contain fractional parts.
    """
    jsonrpc: str = Field(default='2.0', const=True)
    """
    Specifies the version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    result: TaskPushNotificationConfig
    """
    The result object on success.
    """


class GetTaskRequest(A2ABaseModel):
    """
    JSON-RPC request model for the 'tasks/get' method.
    """

    id: str | int
    """
    An identifier established by the Client that MUST contain a String, Number.
    Numbers SHOULD NOT contain fractional parts.
    """
    jsonrpc: str = Field(default='2.0', const=True)
    """
    Specifies the version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    method: str = Field(default='tasks/get', const=True)
    """
    A String containing the name of the method to be invoked.
    """
    params: TaskQueryParams
    """
    A Structured value that holds the parameter values to be used during the invocation of the method.
    """


class JSONRPCErrorResponse(A2ABaseModel):
    """
    Represents a JSON-RPC 2.0 Error Response object.
    """

    error: (
        JSONRPCError
        | JSONParseError
        | InvalidRequestError
        | MethodNotFoundError
        | InvalidParamsError
        | InternalError
        | TaskNotFoundError
        | TaskNotCancelableError
        | PushNotificationNotSupportedError
        | UnsupportedOperationError
        | ContentTypeNotSupportedError
        | InvalidAgentResponseError
    )
    id: str | int | None
    """
    An identifier established by the Client that MUST contain a String, Number.
    Numbers SHOULD NOT contain fractional parts.
    """
    jsonrpc: str = Field(default='2.0', const=True)
    """
    Specifies the version of the JSON-RPC protocol. MUST be exactly "2.0".
    """


class ListTaskPushNotificationConfigSuccessResponse(A2ABaseModel):
    """
    JSON-RPC success response model for the 'tasks/pushNotificationConfig/list' method.
    """

    id: str | int | None
    """
    An identifier established by the Client that MUST contain a String, Number.
    Numbers SHOULD NOT contain fractional parts.
    """
    jsonrpc: str = Field(default='2.0', const=True)
    """
    Specifies the version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    result: list[TaskPushNotificationConfig]
    """
    The result object on success.
    """


class MessageSendConfiguration(A2ABaseModel):
    """
    Configuration for the send message request.
    """

    accepted_output_modes: list[str] = Field(..., alias='acceptedOutputModes')
    """
    Accepted output modalities by the client.
    """
    blocking: bool | None = None
    """
    If the server should treat the client as a blocking request.
    """
    history_length: int | None = Field(default=None, alias='historyLength')
    """
    Number of recent messages to be retrieved.
    """
    push_notification_config: PushNotificationConfig | None = Field(
        default=None, alias='pushNotificationConfig'
    )
    """
    Where the server should send notifications when disconnected.
    """


class OAuthFlows(A2ABaseModel):
    """
    Allows configuration of the supported OAuth Flows
    """

    authorization_code: AuthorizationCodeOAuthFlow | None = Field(
        default=None, alias='authorizationCode'
    )
    """
    Configuration for the OAuth Authorization Code flow. Previously called accessCode in OpenAPI 2.0.
    """
    client_credentials: ClientCredentialsOAuthFlow | None = Field(
        default=None, alias='clientCredentials'
    )
    """
    Configuration for the OAuth Client Credentials flow. Previously called application in OpenAPI 2.0
    """
    implicit: ImplicitOAuthFlow | None = None
    """
    Configuration for the OAuth Implicit flow
    """
    password: PasswordOAuthFlow | None = None
    """
    Configuration for the OAuth Resource Owner Password flow
    """


class Part(A2ABaseModel):
    __root__: TextPart | FilePart | DataPart
    """
    Represents a part of a message, which can be text, a file, or structured data.
    """


class SetTaskPushNotificationConfigRequest(A2ABaseModel):
    """
    JSON-RPC request model for the 'tasks/pushNotificationConfig/set' method.
    """

    id: str | int
    """
    An identifier established by the Client that MUST contain a String, Number.
    Numbers SHOULD NOT contain fractional parts.
    """
    jsonrpc: str = Field(default='2.0', const=True)
    """
    Specifies the version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    method: str = Field(default='tasks/pushNotificationConfig/set', const=True)
    """
    A String containing the name of the method to be invoked.
    """
    params: TaskPushNotificationConfig
    """
    A Structured value that holds the parameter values to be used during the invocation of the method.
    """


class SetTaskPushNotificationConfigSuccessResponse(A2ABaseModel):
    """
    JSON-RPC success response model for the 'tasks/pushNotificationConfig/set' method.
    """

    id: str | int | None
    """
    An identifier established by the Client that MUST contain a String, Number.
    Numbers SHOULD NOT contain fractional parts.
    """
    jsonrpc: str = Field(default='2.0', const=True)
    """
    Specifies the version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    result: TaskPushNotificationConfig
    """
    The result object on success.
    """


class Artifact(A2ABaseModel):
    """
    Represents an artifact generated for a task.
    """

    artifact_id: str = Field(..., alias='artifactId')
    """
    Unique identifier for the artifact.
    """
    description: str | None = None
    """
    Optional description for the artifact.
    """
    extensions: list[str] | None = None
    """
    The URIs of extensions that are present or contributed to this Artifact.
    """
    metadata: dict[str, Any] | None = None
    """
    Extension metadata.
    """
    name: str | None = None
    """
    Optional name for the artifact.
    """
    parts: list[Part]
    """
    Artifact parts.
    """


class DeleteTaskPushNotificationConfigResponse(A2ABaseModel):
    __root__: JSONRPCErrorResponse | DeleteTaskPushNotificationConfigSuccessResponse
    """
    JSON-RPC response for the 'tasks/pushNotificationConfig/delete' method.
    """


class GetTaskPushNotificationConfigResponse(A2ABaseModel):
    __root__: JSONRPCErrorResponse | GetTaskPushNotificationConfigSuccessResponse
    """
    JSON-RPC response for the 'tasks/pushNotificationConfig/set' method.
    """


class ListTaskPushNotificationConfigResponse(A2ABaseModel):
    __root__: JSONRPCErrorResponse | ListTaskPushNotificationConfigSuccessResponse
    """
    JSON-RPC response for the 'tasks/pushNotificationConfig/list' method.
    """


class Message(A2ABaseModel):
    """
    Represents a single message exchanged between user and agent.
    """

    context_id: str | None = Field(default=None, alias='contextId')
    """
    The context the message is associated with
    """
    extensions: list[str] | None = None
    """
    The URIs of extensions that are present or contributed to this Message.
    """
    kind: str = Field(default='message', const=True)
    """
    Event type
    """
    message_id: str = Field(..., alias='messageId')
    """
    Identifier created by the message creator
    """
    metadata: dict[str, Any] | None = None
    """
    Extension metadata.
    """
    parts: list[Part]
    """
    Message content
    """
    reference_task_ids: list[str] | None = Field(default=None, alias='referenceTaskIds')
    """
    List of tasks referenced as context by this message.
    """
    role: Role
    """
    Message sender's role
    """
    task_id: str | None = Field(default=None, alias='taskId')
    """
    Identifier of task the message is related to
    """


class MessageSendParams(A2ABaseModel):
    """
    Sent by the client to the agent as a request. May create, continue or restart a task.
    """

    configuration: MessageSendConfiguration | None = None
    """
    Send message configuration.
    """
    message: Message
    """
    The message being sent to the server.
    """
    metadata: dict[str, Any] | None = None
    """
    Extension metadata.
    """


class OAuth2SecurityScheme(A2ABaseModel):
    """
    OAuth2.0 security scheme configuration.
    """

    description: str | None = None
    """
    Description of this security scheme.
    """
    flows: OAuthFlows
    """
    An object containing configuration information for the flow types supported.
    """
    type: str = Field(default='oauth2', const=True)


class SecurityScheme(A2ABaseModel):
    __root__: (
        APIKeySecurityScheme
        | HTTPAuthSecurityScheme
        | OAuth2SecurityScheme
        | OpenIdConnectSecurityScheme
    )
    """
    Mirrors the OpenAPI Security Scheme Object
    (https://swagger.io/specification/#security-scheme-object)
    """


class SendMessageRequest(A2ABaseModel):
    """
    JSON-RPC request model for the 'message/send' method.
    """

    id: str | int
    """
    An identifier established by the Client that MUST contain a String, Number.
    Numbers SHOULD NOT contain fractional parts.
    """
    jsonrpc: str = Field(default='2.0', const=True)
    """
    Specifies the version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    method: str = Field(default='message/send', const=True)
    """
    A String containing the name of the method to be invoked.
    """
    params: MessageSendParams
    """
    A Structured value that holds the parameter values to be used during the invocation of the method.
    """


class SendStreamingMessageRequest(A2ABaseModel):
    """
    JSON-RPC request model for the 'message/stream' method.
    """

    id: str | int
    """
    An identifier established by the Client that MUST contain a String, Number.
    Numbers SHOULD NOT contain fractional parts.
    """
    jsonrpc: str = Field(default='2.0', const=True)
    """
    Specifies the version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    method: str = Field(default='message/stream', const=True)
    """
    A String containing the name of the method to be invoked.
    """
    params: MessageSendParams
    """
    A Structured value that holds the parameter values to be used during the invocation of the method.
    """


class SetTaskPushNotificationConfigResponse(A2ABaseModel):
    __root__: JSONRPCErrorResponse | SetTaskPushNotificationConfigSuccessResponse
    """
    JSON-RPC response for the 'tasks/pushNotificationConfig/set' method.
    """


class TaskArtifactUpdateEvent(A2ABaseModel):
    """
    Sent by server during sendStream or subscribe requests
    """

    append: bool | None = None
    """
    Indicates if this artifact appends to a previous one
    """
    artifact: Artifact
    """
    Generated artifact
    """
    context_id: str = Field(..., alias='contextId')
    """
    The context the task is associated with
    """
    kind: str = Field(default='artifact-update', const=True)
    """
    Event type
    """
    last_chunk: bool | None = Field(default=None, alias='lastChunk')
    """
    Indicates if this is the last chunk of the artifact
    """
    metadata: dict[str, Any] | None = None
    """
    Extension metadata.
    """
    task_id: str = Field(..., alias='taskId')
    """
    Task id
    """


class TaskStatus(A2ABaseModel):
    """
    TaskState and accompanying message.
    """

    message: Message | None = None
    """
    Additional status updates for client
    """
    state: TaskState
    timestamp: str | None = None
    """
    ISO 8601 datetime string when the status was recorded.
    """


class TaskStatusUpdateEvent(A2ABaseModel):
    """
    Sent by server during sendStream or subscribe requests
    """

    context_id: str = Field(..., alias='contextId')
    """
    The context the task is associated with
    """
    final: bool
    """
    Indicates the end of the event stream
    """
    kind: str = Field(default='status-update', const=True)
    """
    Event type
    """
    metadata: dict[str, Any] | None = None
    """
    Extension metadata.
    """
    status: TaskStatus
    """
    Current status of the task
    """
    task_id: str = Field(..., alias='taskId')
    """
    Task id
    """


class A2ARequest(A2ABaseModel):
    __root__: (
        SendMessageRequest
        | SendStreamingMessageRequest
        | GetTaskRequest
        | CancelTaskRequest
        | SetTaskPushNotificationConfigRequest
        | GetTaskPushNotificationConfigRequest
        | TaskResubscriptionRequest
        | ListTaskPushNotificationConfigRequest
        | DeleteTaskPushNotificationConfigRequest
    )
    """
    A2A supported request types
    """


class AgentCard(A2ABaseModel):
    """
    An AgentCard conveys key information:
    - Overall details (version, name, description, uses)
    - Skills: A set of capabilities the agent can perform
    - Default modalities/content types supported by the agent.
    - Authentication requirements
    """

    capabilities: AgentCapabilities
    """
    Optional capabilities supported by the agent.
    """
    default_input_modes: list[str] = Field(..., alias='defaultInputModes')
    """
    The set of interaction modes that the agent supports across all skills. This can be overridden per-skill.
    Supported media types for input.
    """
    default_output_modes: list[str] = Field(..., alias='defaultOutputModes')
    """
    Supported media types for output.
    """
    description: str
    """
    A human-readable description of the agent. Used to assist users and
    other agents in understanding what the agent can do.
    """
    documentation_url: str | None = Field(default=None, alias='documentationUrl')
    """
    A URL to documentation for the agent.
    """
    icon_url: str | None = Field(default=None, alias='iconUrl')
    """
    A URL to an icon for the agent.
    """
    name: str
    """
    Human readable name of the agent.
    """
    provider: AgentProvider | None = None
    """
    The service provider of the agent
    """
    security: list[dict[str, list[str]]] | None = None
    """
    Security requirements for contacting the agent.
    """
    security_schemes: dict[str, SecurityScheme] | None = Field(
        default=None, alias='securitySchemes'
    )
    """
    Security scheme details used for authenticating with this agent.
    """
    skills: list[AgentSkill]
    """
    Skills are a unit of capability that an agent can perform.
    """
    supports_authenticated_extended_card: bool | None = Field(
        default=None, alias='supportsAuthenticatedExtendedCard'
    )
    """
    true if the agent supports providing an extended agent card when the user is authenticated.
    Defaults to false if not specified.
    """
    url: str
    """
    A URL to the address the agent is hosted at.
    """
    version: str
    """
    The version of the agent - format is up to the provider.
    """


class Task(A2ABaseModel):
    artifacts: list[Artifact] | None = None
    """
    Collection of artifacts created by the agent.
    """
    context_id: str = Field(..., alias='contextId')
    """
    Server-generated id for contextual alignment across interactions
    """
    history: list[Message] | None = None
    id: str
    """
    Unique identifier for the task
    """
    kind: str = Field(default='task', const=True)
    """
    Event type
    """
    metadata: dict[str, Any] | None = None
    """
    Extension metadata.
    """
    status: TaskStatus
    """
    Current status of the task
    """


class CancelTaskSuccessResponse(A2ABaseModel):
    """
    JSON-RPC success response model for the 'tasks/cancel' method.
    """

    id: str | int | None
    """
    An identifier established by the Client that MUST contain a String, Number.
    Numbers SHOULD NOT contain fractional parts.
    """
    jsonrpc: str = Field(default='2.0', const=True)
    """
    Specifies the version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    result: Task
    """
    The result object on success.
    """


class GetTaskSuccessResponse(A2ABaseModel):
    """
    JSON-RPC success response for the 'tasks/get' method.
    """

    id: str | int | None
    """
    An identifier established by the Client that MUST contain a String, Number.
    Numbers SHOULD NOT contain fractional parts.
    """
    jsonrpc: str = Field(default='2.0', const=True)
    """
    Specifies the version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    result: Task
    """
    The result object on success.
    """


class SendMessageSuccessResponse(A2ABaseModel):
    """
    JSON-RPC success response model for the 'message/send' method.
    """

    id: str | int | None
    """
    An identifier established by the Client that MUST contain a String, Number.
    Numbers SHOULD NOT contain fractional parts.
    """
    jsonrpc: str = Field(default='2.0', const=True)
    """
    Specifies the version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    result: Task | Message
    """
    The result object on success
    """


class SendStreamingMessageSuccessResponse(A2ABaseModel):
    """
    JSON-RPC success response model for the 'message/stream' method.
    """

    id: str | int | None
    """
    An identifier established by the Client that MUST contain a String, Number.
    Numbers SHOULD NOT contain fractional parts.
    """
    jsonrpc: str = Field(default='2.0', const=True)
    """
    Specifies the version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    result: Task | Message | TaskStatusUpdateEvent | TaskArtifactUpdateEvent
    """
    The result object on success
    """


class CancelTaskResponse(A2ABaseModel):
    __root__: JSONRPCErrorResponse | CancelTaskSuccessResponse
    """
    JSON-RPC response for the 'tasks/cancel' method.
    """


class GetTaskResponse(A2ABaseModel):
    __root__: JSONRPCErrorResponse | GetTaskSuccessResponse
    """
    JSON-RPC response for the 'tasks/get' method.
    """


class JSONRPCResponse(A2ABaseModel):
    __root__: (
        JSONRPCErrorResponse
        | SendMessageSuccessResponse
        | SendStreamingMessageSuccessResponse
        | GetTaskSuccessResponse
        | CancelTaskSuccessResponse
        | SetTaskPushNotificationConfigSuccessResponse
        | GetTaskPushNotificationConfigSuccessResponse
    )
    """
    Represents a JSON-RPC 2.0 Response object.
    """


class SendMessageResponse(A2ABaseModel):
    __root__: JSONRPCErrorResponse | SendMessageSuccessResponse
    """
    JSON-RPC response model for the 'message/send' method.
    """


class SendStreamingMessageResponse(A2ABaseModel):
    __root__: JSONRPCErrorResponse | SendStreamingMessageSuccessResponse
    """
    JSON-RPC response model for the 'message/stream' method.
    """
